a=input( 'digite algo ')
print('o tipo primitivo deste valor é',type(a))
print('Só tem espaço?',a.isspace())
print('Só tem numero?',a.isnumeric())
print('é alfabetico?',a.isalpha())
print('é alfanumerico?',a.isalnum())
print('Só tem maiuscula ?',a.isupper())
print('Só tem minuscula?',a.islower())
print('Esta capitalizada?',a.istitle())